LOAD DATA LOCAL INFILE '//home//kdasgupta//workspace//hotelgenome//ean_data//ActivePropertyList.txt'  INTO TABLE EAN_ActiveProperties  FIELDS TERMINATED BY '|'  IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '//home//kdasgupta//workspace//hotelgenome//ean_data//AttributeList.txt'  INTO TABLE EAN_Attributes  FIELDS TERMINATED BY '|'  IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '//home//kdasgupta//workspace//hotelgenome//ean_data//GDSAttributeList.txt'  INTO TABLE EAN_GDSAttributes  FIELDS TERMINATED BY '|'  IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '//home//kdasgupta//workspace//hotelgenome//ean_data//DiningDescriptionList.txt'  INTO TABLE EAN_DiningDescriptions  FIELDS TERMINATED BY '|'  IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '//home//kdasgupta//workspace//hotelgenome//ean_data//DiningDescriptionsList.txt'  INTO TABLE EAN_DiningDescriptions  FIELDS TERMINATED BY '|'  IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '//home//kdasgupta//workspace//hotelgenome//ean_data//DiningDescriptionLIst.txt'  INTO TABLE EAN_DiningDescriptions  FIELDS TERMINATED BY '|'  IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '//home//kdasgupta//workspace//hotelgenome//ean_data//GDSAttributePropertyLink.txt'  INTO TABLE EAN_GDSPropertyAttributeLink  FIELDS TERMINATED BY '|'  IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '//home//kdasgupta//workspace//hotelgenome//ean_data//GDSPropertyAttributeLink.txt'  INTO TABLE EAN_GDSPropertyAttributeLink  FIELDS TERMINATED BY '|'  IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '//home//kdasgupta//workspace//hotelgenome//ean_data//PropertyAttributeLink.txt'  INTO TABLE EAN_PropertyAttributeLink  FIELDS TERMINATED BY '|'  IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '//home//kdasgupta//workspace//hotelgenome//ean_data//PropertyDescriptionList.txt'  INTO TABLE EAN_PropertyDescriptions  FIELDS TERMINATED BY '|'  IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '//home//kdasgupta//workspace//hotelgenome//ean_data//PropertyTypeList.txt'  INTO TABLE EAN_PropertyTypes  FIELDS TERMINATED BY '|'  IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '//home//kdasgupta//workspace//hotelgenome//ean_data//RecreationDescriptionList.txt'  INTO TABLE EAN_RecreationDescriptions  FIELDS TERMINATED BY '|'  IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '//home//kdasgupta//workspace//hotelgenome//ean_data//RoomTypeList.txt'  INTO TABLE EAN_RoomTypes  FIELDS TERMINATED BY '|'  IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '//home//kdasgupta//workspace//hotelgenome//ean_data//SpaDescriptionList.txt'  INTO TABLE EAN_SpaDescriptions  FIELDS TERMINATED BY '|'  IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '//home//kdasgupta//workspace//hotelgenome//ean_data//WhatToExpectList.txt'  INTO TABLE EAN_WhatToExpect  FIELDS TERMINATED BY '|'  IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '//home//kdasgupta//workspace//hotelgenome//ean_data//PropertyDescriptionList.txt'  INTO TABLE EAN_PropertyDescriptions CHARACTER SET binary FIELDS TERMINATED BY '|'  IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '//home//kdasgupta//workspace//hotelgenome//ean_data//ParentRegionList.txt'  INTO TABLE EAN_Regions CHARACTER SET binary FIELDS TERMINATED BY '|'  IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '//home//kdasgupta//workspace//hotelgenome//ean_data//RegionEANHotelIDMapping.txt'  INTO TABLE EAN_RegionPropertyMapping CHARACTER SET binary FIELDS TERMINATED BY '|'  IGNORE 1 LINES;
